docs:
  image: ruby:2.1.5
  working_dir: /app
  environment:
    RUBYOPT: "-E utf-8"
    SSH_AUTH_SOCK: "/ssh-agent"
  volumes:
    - ".:/app"
    - "$SSH_AUTH_SOCK:/ssh-agent"
  command: /app/bin/deploy
